### ISSUE TITLE
502: Bad Gateway, 

### ISSUE THREAD

**Issue by banane-m** [KastB/addon-fhem#1]
502: Bad Gateway - no gateway after installation, as if the port wasn't passed through properly, 
maybe someone can help me. 

Thanks, regards Matthias

**Comment by banane-m** [comment]
there is the possibility to route the telnet port through

**Comment by KastB** [comment]
What does the log tell you?
Is fhem running?
Where does the 502 occur? Within Hassio? Can you access the redirected port directly (e.g. hassioip:8083)?

**Comment by banane-m** [comment]
Der 502: Bad Gateway Fehler kommt, wenn man die Weboberfläche aus dem Homeassistant Menü heraus aufruft. 
Bei direkter Einwahl auf die Weboberfläche funktioniert es.
Wäre die Freischaltung bzw. die Weiterleitung des Telnet-Ports nach außen möglich?

**Comment by KastB** [comment]
You are right. Ingress is not configured correctly. I will have a look at it.

The telnet part - I addressed it in the other issue already. I would need more information about that.

**Comment by banane-m** [comment]
after update to version 002 comes "404: Not Found"

**Comment by KastB** [comment]
unfortunately ingress is harder to implement than I thought.
I deactivated it for now, but feel free to do a merge-request if you got it running for you.
I'm not even sure if changes to the website would be required.
Maybe you can try: https://github.com/tux2000/home-assistant-addons/tree/21e1402a63dd264ff55f5f37d0881378a0d8b332

**Comment by banane-m** [comment]
config.json, is the  ""ingress_port": 8083," correct ?

**Comment by banane-m** [comment]
I set it up as a local addon, but I can't find the problem. After restarting the addon, fhem.cfg is reset to default

the complete addon_fhem_docker is completely re-created / rebuild after a normaly restart

**Comment by KastB** [comment]
That rebuild is kind of normal I guess.
I think this is the way fhem designed its docker image.
The fhem.cfg, however, is/should be persistent as this file is mounted from outside (from the homeassistant config folder "/usr/share/hassio/homeassistant/fhem/")

**Comment by banane-m** [comment]
Unfortunately this does not work, neither with addon install with repository or with local addon ->

The fhem.cfg, however, is/should be persistent as this file is mounted from outside (from the homeassistant config folder "/usr/share/hassio/homeassistant/fhem/")

**Comment by KastB** [comment]
What I do is to modify the files in "/usr/share/hassio/addons/git/808d3e2c/addon-fhem/fhem", increment the version number, restart homeassistant, and install the update that pops up then.
If I'm done with my changes I can directly commit and push in this folder with git.

You are right with the persistency: there seems to be an error, which also occurs in the log (bind-mount does not work)

**Comment by banane-m** [comment]
in the dockerfile is:

Copy data for add on
RUN rm -rf /opt/fehm

correct ?

**Comment by KastB** [comment]
So: There should be a fix for the persistency issue now: Apparmor prevented a bind mount.

I'm not sure about those lines: What is your question there?

**Comment by banane-m** [comment]
works, thank you very much
