### ISSUE TITLE
Breaking Home Assistant

### ISSUE THREAD

**Issue by Zaleo80** [KastB/addon-fhem#4]
Using the haos_rpi4-64-9.5 image and installing this Add-On will break Home Assistant from rebooting successfully.

As the Raspberry Pi does not boot correctly I can't find a way to collect more logging information, however I found that once this Add-On is installed and started all seems to work but the upgrade process of NodeJs within FHEM it self (Outdated) is breaking the HA instance.

Would love to run FHEM as an add-on next to HA on one Pi for my CUL/CUN devices (FS20).

**Comment by KastB** [comment]
Do you have any updates on this?
The information provided is quite limited.
I have no haos image installed, but a raspian with hassio and didn't notice any issues.
