### ISSUE TITLE
Q: possible to upload custom files/tools to addon?

### ISSUE THREAD

**Issue by SpaceTeddy** [KastB/addon-fhem#6]
Dear KastB,
on my native fhem installation, I use some custom python scripts which I call from fhem. In addition I use mosquitto on my fhem/pi.
Is it possible, that I can upload my special tools to the ad-on? and if yes, how to do this?

thanks a lot for your help.

cu
chris

**Comment by KastB** [comment]
For the homeassistant folder (normally /usr/share/hassio/homeassistant), where all your configuration sits, should be mounted to /config within the fhem container. So if you place your scripts/whatever in this folder, you can access them from within your container. I don't know how you want call them then, however.
